# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/oppo-source/android_kernel_oppo_mt6833/tree/oppo/mt6833_t_13.0_a58_5g
          kernel-dir: msm-4.19
          kernel-branch: oppo/mt6833_t_13.0_a58_5g
          config: k6833v1_64_k419_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
